var wolverine = new Image(); wolverine.src="https://www.spriters-resource.com/resources/sheets/29/31849.png";
var captainamerica = new Image(); captainamerica.src="https://www.spriters-resource.com/resources/sheets/29/32123.png";
var redHulk = new Image(); redHulk.src="https://www.spriters-resource.com/resources/sheets/51/54505.png";
var redHulkFliped = new Image(); redHulkFliped.src="images/redHulkfliped.png";
var greenHulk = new Image(); greenHulk.src="https://i.pinimg.com/originals/00/0f/9a/000f9af3da995c1f208fc5896fa81b6e.gif";
var ironman = new Image(); ironman.src="https://i.pinimg.com/originals/22/90/83/229083d9549d05c7d8821732dcca5606.gif";
var hawkEye = new Image(); ironman.src="https://www.spriters-resource.com/resources/sheets/45/48225.png";
var greenHulk2 = new Image(); greenHulk2.src="https://www.spriters-resource.com/resources/sheets/63/66595.png";
var greenHulk2Fliped = new Image(); greenHulk2Fliped.src="images/greenHulkFliped.png";
